use_frameworks!

platform :ios, '11.0'

target 'SeedSegmentedControl_Example' do
  pod 'SeedSegmentedControl', :path => '../'

  target 'SeedSegmentedControl_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
