use_frameworks!

platform :ios, '8.0'

target 'SeedSegmentedView_Example' do
  pod 'SeedSegmentedView', :path => '../'

  target 'SeedSegmentedView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
